version: '3.8'

services:
  backend:
    build: .
    container_name: emolit-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./static:/app/static
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
    container_name: emolit-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
